version: "3"
services:
  flint.example.api:
    build:
      image: simpleshell/flint-ui-flint.example.api:1.0.0
    ports:
      - "8080:8080"
    container_name: flint.example.api
    volumes:
      - ./flint.cloud/local/rest_api_flint.example/output:/server/output
      - ./flint.cloud/local/rest_api_flint.example/config:/server/config
  flint.gcbm.api:
    image: 
    ports:
      - "8081:8080"
    container_name: flint.gcbm.api
    volumes:
      - ./flint.cloud/local/rest_api_gcbm/output:/server/output
      - ./flint.cloud/local/rest_api_gcbm/config:/server/config
  flint.ui:
    image: simpleshell/flint-ui-flint.ui:1.0.0
    ports:
      - "8000:80"
    container_name: flint.ui
    volumes:
      - ./flint.ui:/usr/src/app/flint.ui
      - ./flint.cloud/local/rest_api_flint.example/output:/server/output
      - /usr/src/app/flint.ui/node_modules
  # storybook:
  #   container_name: storybook
  #   ports:
  #     - "6006:6006"
  #   build:
  #     context: ./flint.ui
  #     dockerfile: ./.storybook/Dockerfile
