version: "3"
services:
  flint.example.api:
    build:
      context: ./flint-api/local/rest_api_flint.example
      dockerfile: Dockerfile
    image: simpleshell/flint.example.api:latest
    ports:
      - "8080:8080"
    container_name: flint.example.api
    volumes:
      - ./flint-api/local/rest_api_flint.example/output:/server/output
      - ./flint-api/local/rest_api_flint.example/config:/server/config

  flint.gcbm.api:
    build:
      context: ./flint-api/local/rest_api_gcbm/
      dockerfile: Dockerfile
    image: simpleshell/flint.gcbm.api:latest
    ports:
      - "8081:8080"
    container_name: flint.gcbm.api
    volumes:
      - ./flint-api/local/rest_api_gcbm/output:/server/output
      - ./flint-api/local/rest_api_gcbm/config:/server/config
      - shared-output:/app/output

  viz.api:
    build:
      context: ./viz-api
      dockerfile: Dockerfile
    image: simpleshell/viz.api:latest
    ports:
      - "8082:8080"
    container_name: viz.api
    volumes:
      - ./viz-api/output:/server/output
      - ./viz-api/config:/server/config
      - shared-output:/shared-output

  user.ui:
    build:
      context: ./user-ui
      dockerfile: Dockerfile
    image: simpleshell/user.ui:latest
    ports:
      - "8000:80"
    container_name: user.ui
    volumes:
      - ./user-ui:/usr/src/app/user-ui
      - ./flint.api/local/rest_api_flint.example/output:/server/output
      - /usr/src/app/user-ui/node_modules

  data.api:
    build:
      context: ./data-api
      dockerfile: Dockerfile
    image: simpleshell/data.api:latest
    ports:
      - "8083:8080"
    container_name: data.api
    volumes:
      - ./data-api/output:/server/output
      - ./data-api/config:/server/config
      - shared-input:/app/datasets

volumes:
  shared-output:
  shared-input:
