name: taswira
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.6
  - numpy=1.19.5
  - rasterio>=1.0
  - shapely
  - gunicorn
  - crick
  - pip
  - pip:
    - terracotta==0.6.0
    - pytest>=5.2
    - pylint>=2.5.2
    - dash==1.13.3
    - dash-leaflet==0.0.19
    - MarkupSafe==2.0.1
    - taswira==0.1.2

